/*
 * XT28ReadSensorsPrivate.h
 *
 *  Created on: 23 nov. 2015
 *      Author: ladmin
 */

#ifndef _XT28READSENSORSPRIVATE_H_
#define _XT28READSENSORSPRIVATE_H_

//---------------------DEFINES index for the global variable angleData -------------------
#define ANALOG_RIGHT_FRONT_PENDULUMARM	 	0
#define ANALOG_LEFT_FRONT_PENDULUMARM	 	1
#define ANALOG_RIGHT_MID_PENDULUMARM	 	2
#define ANALOG_LEFT_MID_PENDULUMARM 		3
#define ANALOG_RIGHT_BACK_PENDULUMARM 		4
#define ANALOG_LEFT_BACK_PENDULUMARM		5
#define INDEX_SIZE_WHEELS				    6

//---------------------DEFINES index for the global variable pressure sensors ------------
#define ANALOG_FRONT_RIGHT_PENDULUM_PRESSURE_A			0
#define ANALOG_FRONT_RIGHT_PENDULUM_PRESSURE_B			1
#define ANALOG_FRONT_LEFT_PENDULUM_PRESSURE_A			2
#define ANALOG_FRONT_LEFT_PENDULUM_PRESSURE_B			3
#define ANALOG_MID_RIGHT_PENDULUM_PRESSURE_A			4
#define ANALOG_MID_RIGHT_PENDULUM_PRESSURE_B			5
#define ANALOG_MID_LEFT_PENDULUM_PRESSURE_A				6
#define ANALOG_MID_LEFT_PENDULUM_PRESSURE_B				7
#define ANALOG_REAR_RIGHT_PENDULUM_PRESSURE_A			8
#define ANALOG_REAR_RIGHT_PENDULUM_PRESSURE_B			9
#define ANALOG_REAR_LEFT_PENDULUM_PRESSURE_A			10
#define ANALOG_REAR_LEFT_PENDULUM_PRESSURE_B			11
#define INDEX_SIZE_PRESSURESENS							12

#endif /* TEMPLATE_XT28READSENSORSPRIVATE_H_ */
