Forwarder XT28 API Documentation: Excipad right
Excipad right
Driver interface
Description of module
Right excipad buttons and joystick.
Does the following:
Setup right excipad
Get what button driver have pressed
Get joystick value.
Configure
void EXPConfigureExcipad (uint8 CANChannel, int buttonDataboxNr, int joystrickDataboxYNr, int joystickDataboxXNr)
bool EXPCheckTimeout (int callTime_ms, int timeoutTime_ms)
Get
exipadButton EXPGetLastPressedButtonWithToggle (void)
exipadButton EXPGetCurrentlyPressedButton (void)
bool EXPGetUserIsHoldingAButtonDown (void)
float EXPGetJoystickScaledValueUppDown (void)
float EXPGetJoystickXScaledValueLeftRight (void)
Set
void EXPSetButtonStateTo (exipadButton setButtonState)
Enumeration Type Documentation
enum exipadButton
Excipad Button Enum. Used for Excipad related functions.
Enumerator
NONE
No Button pressed
BUTTON_1
Button 1
BUTTON_2
Button 2
BUTTON_3
Button 3
BUTTON_4
Button 4
BUTTON_5
Button 5
BUTTON_6
Button 6
BUTTON_7
Button 7
BUTTON_8
Button 8
BUTTON_9
Button 9
BUTTON_10
Button 10
BUTTON_11
Button 11
BUTTON_12
Button 12
BUTTON_13
Button 13
BUTTON_14
Button 14
BUTTON_15
Button 15
BUTTON_16
Button 16
BUTTON_17
Button 17
BUTTON_18
Button 18
BUTTON_19
Button 19
BUTTON_20
Button 20
BUTTON_21
Button 21
NONE
No Button pressed
BUTTON_1
Button 1
BUTTON_2
Button 2
BUTTON_3
Button 3
BUTTON_4
Button 4
BUTTON_5
Button 5
BUTTON_6
Button 6
BUTTON_7
Button 7
BUTTON_8
Button 8
BUTTON_9
Button 9
BUTTON_10
Button 10
BUTTON_11
Button 11
BUTTON_12
Button 12
BUTTON_13
Button 13
BUTTON_14
Button 14
BUTTON_15
Button 15
BUTTON_16
Button 16
BUTTON_17
Button 17
BUTTON_18
Button 18
BUTTON_19
Button 19
BUTTON_20
Button 20
BUTTON_21
Button 21
Function Documentation
bool EXPCheckTimeout (int callTime_ms, int timeoutTime_ms)
Check if exipad have timedout, if it has the actuate should disable.
Parameters
callTime_ms
timeoutTime_ms
Returns
void EXPConfigureExcipad (uint8 CANChannel, int buttonDataboxNr, int joystrickDataboxYNr, int joystickDataboxXNr)
This function is mandatory to call in the setup of the program if you need to use this module. This function sets up what channel the Excipad is connected. The setup require to use two data boxes in the BODAS C-API. Any channels can be used that is valid by the BODAS API and is not used by any other channel.
Parameters
[in] CANChannel The CAN channel the Excipad is connected.
[in] buttonDataboxNr A data box number, valid range is [1 - 100]
[in] joystrickDataboxNr A data box number, valid range is [1 - 100]
exipadButton EXPGetCurrentlyPressedButton (void)
Get the currently pressed button
References BUTTON_1, BUTTON_10, BUTTON_11, BUTTON_12, BUTTON_13, BUTTON_14, BUTTON_15, BUTTON_16, BUTTON_17, BUTTON_18, BUTTON_19, BUTTON_2, BUTTON_20, BUTTON_21, BUTTON_3, BUTTON_4, BUTTON_5, BUTTON_6, BUTTON_7, BUTTON_8, BUTTON_9, and NONE.
Referenced by EXPGetLastPressedButtonWithToggle().
float EXPGetJoystickScaledValueUppDown (void)
Get the scaled value of the excipad joy stick.
Returns
Int values in range [-400 - 400]
References NONE.
float EXPGetJoystickXScaledValueLeftRight (void)
Get the scaled value of the excipad joystick Left right X
Parameters
setButtonState
exipadButton EXPGetLastPressedButtonWithToggle (void)
Get the last button that was pressed. If the user pressed the button again this function will return NONE, will return a !lastbutton.
Returns
exipadButton last pressed, toggled if pressed again.
References EXPGetCurrentlyPressedButton(), EXPGetUserIsHoldingAButtonDown(), and NONE.
bool EXPGetUserIsHoldingAButtonDown (void)
Check if the user is currently pressing a button on the excipad
Referenced by EXPGetLastPressedButtonWithToggle().
void EXPSetButtonStateTo (exipadButton setButtonState)
Sets the last pressed button to state NONE.